version: '3.1'

services:
  ledger-client:
    build: ../
    ports:
    - 8091:8091
    depends_on:
    - db
    environment:
    - DB_HOST=6c27a0e6dbd0
    - DB_SCHEMA=utavi-ledger-db
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - FABRIC_HOST=localhost

  db:
    image: postgres
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=utavi-ledger-db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
