server:
  port: 8091
  undertow:
    io-threads: 8

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: docker
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          temp:
            use_jdbc_metadata_defaults: false

management:
  endpoint:
    health:
      show-details: always

scheduling:
  reenroll:
    enabled: false

caching:
  enabled: false

aws:
  region: us-east-1
  bucket:
    chaincode:
      name: utavi-chaincode-repository
      prefix: stable
      branch: master
  sqs:
    tx-processing-queue: ${TX_PROCESSING_QUEUE}

chaincode-location: s3

hl:
  resourceServer:
    url: ${RESOURCE_SERVER_SCHEME:http}://${RESOURCE_SERVER_HOST:resource-server}:${RESOURCE_SERVER_PORT:9000}
  host: ${FABRIC_HOST}
  lator:
    url: ${LATOR_SCHEME:http}://${LATOR_HOST:admin-tools.utavi.com}:${LATOR_PORT:7059}
  channel-profile: OrgsChannel
  sdk-version: @hf.sdk.version@
  proposal-wait-time:
    user-transaction: 90000
    admin-transaction: 120000

# AES only supports key sizes of 16, 24 or 32 bytes.
crypt:
  secretkey: ${CRYPT_SECRETKEY:TheBestSecretKey}

organization:
  peer:
    channel-num: ${CHANNEL_NUM}
    peers-per-channel: ${PEERS_PER_CHANNEL}
    start-port: ${PEER_START_PORT}
    admin:
      name: ${PEER_ORG_ADMIN_NAME:admin.main-utavi}
      password: ${PEER_ORG_ADMIN_PASSWORD:admin.main-utavipw}
    ica:
      start-port: ${PEER_ORG_ICA_START_PORT}
      bootstrap-user: ${ICA_MAIN_BOOTSTRAP_USER:main-utavi-ica-bootstrap-identity}
      bootstrap-pw: ${ICA_MAIN_BOOTSTRAP_PW:main-utavi-ica-bootstrap-identitypw}

  orderer:
    start-port: ${ORDERER_START_PORT}
    admin:
      name: ${ORDERER_ORG_ADMIN_NAME:admin.orderer-utavi}
      password: ${ORDERER_ORG_ADMIN_PASSWORD:admin.orderer-utavipw}
    ica:
      start-port: ${ORDERER_ORG_ICA_START_PORT}
      bootstrap-user: ${ICA_ORDERER_BOOTSTRAP_USER:orderer-utavi-ica-bootstrap-identity}
      bootstrap-pw: ${ICA_ORDERER_BOOTSTRAP_PW:orderer-utavi-ica-bootstrap-identitypw}

executor:
  pool:
    core-size: 8
    max-size: 24
    queue-capacity: 200

application:
  version: ${VERSION:not_specified}
